#RELACIONAMENTO ENTRE A TABELA ITENS PEDIDOS E A TABELA PRODUTOS
ALTER TABLE tbl_iten_pedido ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (cod_prod)
REFERENCES tbl_produto(cod_prod);

#RELACIONAMENTO ENTRE A TABELA ITENS PEDIDOS E A TABELA PEDIDOS
ALTER TABLE tbl_iten_pedido ADD CONSTRAINT FK_PEDIDOS
FOREIGN KEY (cod_ped)
REFERENCES tbl_pedido(cod_ped);